
package ru.bvn13.licenseserverjclient.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckLicenseWSService", targetNamespace = "http://checkLicenseJ.bvn13.ru", wsdlLocation = "http://licenseserverj.cf/ws/checkLicense?WSDL")
public class CheckLicenseWSService
    extends Service
{

    private final static URL CHECKLICENSEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKLICENSEWSSERVICE_EXCEPTION;
    private final static QName CHECKLICENSEWSSERVICE_QNAME = new QName("http://checkLicenseJ.bvn13.ru", "CheckLicenseWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://licenseserverj.cf/ws/checkLicense?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKLICENSEWSSERVICE_WSDL_LOCATION = url;
        CHECKLICENSEWSSERVICE_EXCEPTION = e;
    }

    public CheckLicenseWSService() {
        super(__getWsdlLocation(), CHECKLICENSEWSSERVICE_QNAME);
    }

    public CheckLicenseWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKLICENSEWSSERVICE_QNAME, features);
    }

    public CheckLicenseWSService(URL wsdlLocation) {
        super(wsdlLocation, CHECKLICENSEWSSERVICE_QNAME);
    }

    public CheckLicenseWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKLICENSEWSSERVICE_QNAME, features);
    }

    public CheckLicenseWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckLicenseWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckLicenseJ
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public CheckLicenseJ getSOAPOverHTTP() {
        return super.getPort(new QName("http://checkLicenseJ.bvn13.ru", "SOAPOverHTTP"), CheckLicenseJ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckLicenseJ
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public CheckLicenseJ getSOAPOverHTTP(WebServiceFeature... features) {
        return super.getPort(new QName("http://checkLicenseJ.bvn13.ru", "SOAPOverHTTP"), CheckLicenseJ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKLICENSEWSSERVICE_EXCEPTION!= null) {
            throw CHECKLICENSEWSSERVICE_EXCEPTION;
        }
        return CHECKLICENSEWSSERVICE_WSDL_LOCATION;
    }

}
