
package ru.bvn13.licenseserverjclient.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "checkLicenseJ", targetNamespace = "http://checkLicenseJ.bvn13.ru")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckLicenseJ {


    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "checkLicenseResponse", targetNamespace = "http://checkLicenseJ.bvn13.ru", partName = "parameters")
    public Object checkLicense(
        @WebParam(name = "checkLicense", targetNamespace = "http://checkLicenseJ.bvn13.ru", partName = "parameters")
        CheckLicense parameters);

}
