
package ru.bvn13.licenseserverjclient.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckLicenseWS", targetNamespace = "http://checkLicenseJ.bvn13.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckLicenseWS {


    /**
     * 
     * @param request
     * @return
     *     returns ru.bvn13.licenseserverjclient.soap.CheckClientLicenseResponse.Response
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkClientLicense", targetNamespace = "http://checkLicenseJ.bvn13.ru", className = "ru.bvn13.licenseserverjclient.soap.CheckClientLicense")
    @ResponseWrapper(localName = "checkClientLicenseResponse", targetNamespace = "http://checkLicenseJ.bvn13.ru", className = "ru.bvn13.licenseserverjclient.soap.CheckClientLicenseResponse")
    public ru.bvn13.licenseserverjclient.soap.CheckClientLicenseResponse.Response checkClientLicense(
        @WebParam(name = "request", targetNamespace = "")
        ru.bvn13.licenseserverjclient.soap.CheckClientLicense.Request request);

}
